backend:
  name: github
  repo: laiscavalcanti/subsidiario.com
  branch: main # Branch to update (optional; defaults to master)
  site_domain: https://infoseeker.netlify.app/

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
site_url: https://infoseeker.netlify.app/
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: blog
    label: Blog
    folder: content/blog
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    create: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - label: 'Post Tags'
        name: 'postTags'
        widget: 'select'
        multiple: true
        min: 1
        max: 2
        options:
          - { label: "Chicago", value: "ORD" }
          - { label: "Paris", value: "CDG" }
          - { label: "Tokyo", value: "HND" }